## numpy.whereによる条件制御

In [9]:
"""
numpy.where(条件の配列, Xのデータ, Yのデータ)
条件の配列がTrueの時はXのデータ、そうでなければYのデータを取り出す
"""

x_array= np.array([1,2,3,4,5])
y_array= np.array([6,7,8,9,10])

bool_data = np.array([False, False, True, True, False])
print(np.where(bool_data, x_array, y_array))

[ 6  7  3  4 10]


## 行方向の結合

In [15]:
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])
sample_array3, sample_array4

(array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]]))

In [16]:
# vstackを使って行方向に結合する
np.vstack((sample_array3, sample_array4))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## 列方向の結合

In [17]:
# hstackを使って列方向に結合する
np.hstack((sample_array3, sample_array4))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

## 配列の分割

In [18]:
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])
sample_array_vstack = np.vstack((sample_array3, sample_array4))

In [19]:
# splitを使って分割
first, second, third = np.split(sample_array_vstack, [1,3])

print(first)

[[1 2 3]]


In [20]:
print(second)

[[4 5 6]
 [7 8 9]]


In [21]:
print(third)

[[10 11 12]]
