- dtypeは要素の型を確認する
- ndimは次元の数を確認する


In [1]:
import numpy as np

In [2]:
# 要素が全て１の多次元配列を作成
np_ones_23 = np.ones((2,3))
np_ones_23

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
# 多次元配列の要素を全て入れ替える
np_zeros_like_23 = np.zeros_like(np_ones_23)
np_zeros_like_23

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# 単位行列を作成
np_eye_3 = np.eye(3)
np_eye_3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
# 対角行列を作成
np_diag = np.diag([10,11,12])
np_diag

array([[10,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 12]])

## 乱数

In [6]:
# 0から3の乱数（多次元）
rnd2 = np.random.randint(0,3,(2,5))
rnd2

array([[2, 0, 1, 1, 2],
       [1, 1, 1, 0, 0]])

In [7]:
# リストからランダムに選択
targets = ['A', 'B', 'C']
rnd3 = np.random.choice(targets, 4)
rnd3

array(['C', 'B', 'C', 'C'], dtype='<U1')

In [8]:
# リストからランダムに最大で1度だけ選択
rnd4 = np.random.choice(targets, 3, replace=False)
rnd4

array(['A', 'C', 'B'], dtype='<U1')

In [9]:
# リストの順番をランダムに（元のリストはそのまま）
rnd5 = np.random.permutation(targets)
rnd5

array(['A', 'C', 'B'], dtype='<U1')