In [1]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series,DataFrame

# 線形代数用のライプラリ
import scipy.linalg as linalg

# 最適化計算（最小値）用の関数
from scipy.optimize import minimize_scalar

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

%precision 3

'%.3f'

In [5]:
# ndim: 次元数を確認する
print('次元数:', data.ndim)

次元数: 1


In [6]:
# size: 要素数を確認する
print('要素数:', data.size)

要素数: 10


In [8]:
# sort: 要素を並び替える。immutableなメソッド
data.sort()
print('ソート後:', data)

ソート後: [ 1  2  3  4  5  6  7  8  9 10]


In [9]:
# 降順にソートしたい場合
data[::-1].sort()
print('ソート後:', data)

ソート後: [10  9  8  7  6  5  4  3  2  1]


In [10]:
# cumsum: 前から順に足し上げていく
print(data.cumsum())

[10 19 27 34 40 45 49 52 54 55]


In [3]:
# random.choice(対象の配列, 取り出す数): 与えられたデータ列からランダムなものを取り出す
data = np.array([9,2,3,4,10,6,7,8,1,5])

print(random.choice(data,10))

# 重複無しで抽出（非復元抽出）の場合
print(random.choice(data, 10, replace=False))

[ 8  7  6  9  3  9  1  3  1 10]
[ 5  9  1  4  6  2  3  7 10  8]


In [7]:
# det(): 行列式を求める
matrix = np.array([[1,-1,-1],[-1,1,-1],[-1,-1,1]])
print(linalg.det(matrix))

-4.0


## inv(): 逆行列を求める

In [10]:
print(linalg.inv(matrix))

[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


## eig(): 固有値、固有ベクトルを求める

In [11]:
eig_value, eig_vector = linalg.eig(matrix)

print('固有値: ', eig_value)
print('固有ベクトル: ', eig_vector)

固有値:  [-1.+0.j  2.+0.j  2.+0.j]
固有ベクトル:  [[ 0.577 -0.816  0.428]
 [ 0.577  0.408 -0.816]
 [ 0.577  0.408  0.389]]


In [3]:
attri_data1 = {'ID':['100','101','102','103','104'],
               'City':['Tokyo','Osaka','Kyoto','Hokkaido','Tokyo'],
               'Birth_year':[1990,1989,1992,1997,1982],
               'Name':['Hiroshi','Akiko','Yuki','Satoru','Steve']}

attri_data_frame1 = DataFrame(attri_data1)

print(attri_data_frame1)

    ID      City  Birth_year     Name
0  100     Tokyo        1990  Hiroshi
1  101     Osaka        1989    Akiko
2  102     Kyoto        1992     Yuki
3  103  Hokkaido        1997   Satoru
4  104     Tokyo        1982    Steve


## isin(リスト) : 条件を複数指定してデータを抽出する

In [7]:
attri_data_frame1[attri_data_frame1['City'].isin(['Tokyo','Osaka'])]

ID   City  Birth_year     Name
0  100  Tokyo        1990  Hiroshi
1  101  Osaka        1989    Akiko
4  104  Tokyo        1982    Steve

## axisパラメーター
- **axis=0が行**
- **axis=1が列**

In [8]:
# 列削除
attri_data_frame1.drop(['Birth_year'], axis=1)

ID      City     Name
0  100     Tokyo  Hiroshi
1  101     Osaka    Akiko
2  102     Kyoto     Yuki
3  103  Hokkaido   Satoru
4  104     Tokyo    Steve

In [10]:
attri_data2 = {'ID':['100','101','102','103','104'],
               'City':['Tokyo','Osaka','Kyoto','Hokkaido','Tokyo'],
               'Birth_year':[1990,1989,1992,1997,1982],
               'Name':['Hiroshi','Akiko','Yuki','Satoru','Steve']}
attri_data_frame2 = DataFrame(attri_data2)
attri_data_frame_index2 = DataFrame(attri_data2,index=['e','b','a','d','c'])
attri_data_frame_index2

ID      City  Birth_year     Name
e  100     Tokyo        1990  Hiroshi
b  101     Osaka        1989    Akiko
a  102     Kyoto        1992     Yuki
d  103  Hokkaido        1997   Satoru
c  104     Tokyo        1982    Steve

## sort_index() : インデックスでソートする

In [11]:
attri_data_frame_index2.sort_index()

ID      City  Birth_year     Name
a  102     Kyoto        1992     Yuki
b  101     Osaka        1989    Akiko
c  104     Tokyo        1982    Steve
d  103  Hokkaido        1997   Satoru
e  100     Tokyo        1990  Hiroshi

## sort_values() : 値でソートする

In [12]:
attri_data_frame_index2.Birth_year.sort_values()

c    1982
b    1989
e    1990
a    1992
d    1997
Name: Birth_year, dtype: int64

In [13]:
# 値があるか確認
attri_data_frame_index2.isin(['Tokyo'])

ID   City  Birth_year   Name
e  False   True       False  False
b  False  False       False  False
a  False  False       False  False
d  False  False       False  False
c  False   True       False  False

In [15]:
# 欠損値を調べる

# nameを全てnanにする
attri_data_frame_index2['Name'] = np.nan
# nullを調べる
attri_data_frame_index2.isnull()
# nullを判定し合計する
attri_data_frame_index2.isnull().sum()

ID            0
City          0
Birth_year    0
Name          5
dtype: int64